Title: Dedalus Training Survey
Author: Danilo Gouveia
Image: https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png
Theme: 282828
Questions:
    Question1:
        Type: CheckBox
        Label: "Quais dos serviços abaixo você gostaria uma apresentação?"
            Values:
                Value1: "EC2 - Auto Scalling / Spot"
                Value2: "Statistics on tabs vs spaces adoption"
                Value3: "Other stuff"
                Value4: "S3"
                Value5: "IAM"
                Value6: "Organizations"
                Value7: "RDS"
                Value8: "CloudWatch"
                Value9: "CloudFormation"
                Value10: "Networking - VPN / VPC / TGW / DX"
                Value11: "Cost Explorer / CUR"
    Question2:
        Type: Text
        Label: "Você tem alguma dúvida especifica sobre algum desses serviços?"
    Question3:
        Type: Radio
        Label: "Você acha importante o uso de laboratórios nas apresentações técnicas?"
        Values:
            Value1: Sim
            Value2: Não
    Question4:
        Type: Radio
        Label: "Você prefere ..."
        Values:
            Value1: "Assistir alguém executar o laboratório"
            Value2: "Fazer eu mesmo o laboratório"
